### ISSUE TITLE
beta2 todo list

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/facebook#141]
- [ ] removed all the pug
- [ ] updated README
- [ ] imported stats from fbtrex
- [ ] imported mirror from fbtrex
